sudo: false

language: python

python:
  - 2.7

install:
  - pip install ansible
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook test.yml -i inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
