sudo: false

language: python

python:
  - 2.7

install:
  - pip install ansible
  - ansible-galaxy install --force ansible-fco-haproxy

script:
  - ansible-playbook test.yml -i inventory --syntax-check
  - ansible-galaxy install ansible-fco-haproxy
