sudo: false

language: python

python:
  - 2.7
 
env:
  - distro: ubuntu1404
  
tasks:
- include_tasks: tasks/main.yml
- name: Download and install haproxy
  yum: name=haproxy state=present

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
  
script:
  - ansible-playbook test.yml -i inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
